# Generated by Django 4.1.4 on 2022-12-30 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Joining', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(default=0)),
                ('Bonus', models.IntegerField(default=0)),
                ('Role', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=10)),
            ],
        ),
    ]
